# Generated by Django 3.1.2 on 2020-10-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField(choices=[(1, 'Paid vacation'), (2, 'Unpaid vacation'), (3, 'Illness vacation'), (4, 'Maternity vacation')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('rejection_reason', models.IntegerField(choices=[(1, 'Paid vacation'), (2, 'Unpaid vacation'), (3, 'Illness vacation'), (4, 'Maternity vacation')], null=True)),
                ('confirmed_by', models.ForeignKey(limit_choices_to={'is_approver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_vacations', to='home.vacationsuser')),
                ('rejected_by', models.ForeignKey(limit_choices_to={'is_rejector': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_vacations', to='home.vacationsuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacations', to='home.vacationsuser')),
            ],
        ),
    ]
